export const SEARCH_SEGMENTS = [
  "Academia",
  "Advogado",
  "Barbearia",
  "Clínica estética",
  "Clínica médica",
  "Contabilidade",
  "Dentista",
  "Escola",
  "Farmácia",
  "Fisioterapia",
  "Imobiliária",
  "Loja de roupas",
  "Oficina mecânica",
  "Padaria",
  "Pet shop",
  "Pizzaria",
  "Restaurante",
  "Salão de beleza",
  "Veterinário",
  "Ótica",
] as const;
